import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// SDK Guides sidebar (default/homepage) - this will be the root
	sdkGuidesSidebar: [
		{
			type: 'autogenerated',
			dirName: 'sdk',
		},
	],

	// Core Concepts sidebar
	coreConceptsSidebar: [
		{
			type: 'autogenerated',
			dirName: 'core-concepts',
		},
	],

	// Code examples sidebar
	codeExamplesSidebar: [
		{
			type: 'autogenerated',
			dirName: 'code-examples',
		},
	],

	// Operator guides sidebar
	operatorGuidesSidebar: [
		{
			type: 'autogenerated',
			dirName: 'operators',
		},
	],
};

export default sidebars;
